package errors

import (
	"net/http"

	"github.com/wisdom-oss/common-go/v3/types"
)

// This file contains all errors that are generated by the API during the
// handling of requests.
// The errors are then imported and sent back by using the .Emit

var ErrInvalidMeasurementParameters = types.ServiceError{
	Type:   "https://www.rfc-editor.org/rfc/rfc9110.html#section-15.5.5",
	Status: http.StatusBadRequest,
	Title:  "InvalidMeasurementParameters",
	Detail: "The measurement parameters are invalid. Please check your request",
}
